### ISSUE TITLE
2.1.05

### ISSUE THREAD

**Issue by Seori02** [Zerstorer23/MNDfake#4]
버전 업데이트 가능한가요?

**Comment by Seori02** [comment]
![Screenshot_20220807-130556](https://user-images.githubusercontent.com/109285628/183274788-0e90d974-ac47-4059-b8ee-b5edd05a5d11.png)
소스코드 해석 후 패치 완료

**Comment by Zerstorer23** [comment]
우와 저 국방부앱 없어서 이제 어떻게되가는지도 모르는참이었는데 대단하십니다.
이거 찾는 사람이 좀 있는 모양이던데 프로젝트 이어(?)받아가시는게 어떤가요??

**Comment by Seori02** [comment]
어엌ㅋㅋㅋㅋㅋ
현역 군인이라 위험하지 않을까 싶은데...
이미 만들어버리긴 한지라...
게다가 파일이랑 코드를 제대로 볼줄은 모릅니다...
그냥 딱 원하는 부분만 찾아서 바꿨던거라서...
도움을 주실 수 있다면 이어받아가는것(?)도 나쁘지 않을것 같네요..!

**Comment by Zerstorer23** [comment]
ㄹㅇ 그 앱이 캡쳐도 안되고 그렇다고 내폰에 깔자니 진짜 해제하려면 NFC인증해야되고 현역 사용자가 없으면 유지보수가 힘들어서 근데 리드미 이렇게 적어놨는데도 어떻게 방문자가 존재하는거 보면 참 신기함 저도 가끔 메일이나 이슈 올라오면 참 그립구만 싶은데 현실적으로 어떻게 할수가없음

직접 레포 만들어서 운영하시면 저는 그냥 리드미에 링크라도 걸어드림
권한도 보내드렸으니까 이 레포에 커밋 올려도 되고

**Comment by Seori02** [comment]
구글에다가 국방모바일보안 가짜앱 치면 여기로 링크 걸어놓은 블로그가 있어서 아마 유입 되는 듯 하네요...저도 그랬었고...
저도 국방모바일보안 자체를 어떻게 해보려다가 도저히 못 건드리겠어서 님 소스코드 뜯어서 카메라블록 이미지에 비율 적당히 맞게 1303추가해서 한 사진으로 만들고 아래 버전이랑 설정에서 보이는 앱 정보 버전만 바꾼거라...
사지방 컴퓨터로 했더니 암걸리겠더라고요
로그 남는건 뭐...
나중에 시간 되면 z플립 이외의 폰에도 사용할 수 있게 수정해봐야겠네요
현재로선 z플립 비율에서만 정상작동 테스트가 된거라

**Comment by Zerstorer23** [comment]
와..검색해봤는데 2년새에 엄청난 기술들이 발견되었네요.

**Comment by Seori02** [comment]
일단 병사용이 따로 구분되기도 했고 보안폴더에 설치 제한,루팅된 기기에 설치 제한 걸려서 어떻게 해보기도 쉽지않더라구요...
